In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('./Data.csv')

In [3]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
dataset.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [5]:
X = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1:].values

In [6]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X, y , test_size=0.2 , random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
y_train = sc.fit_transform(y_train)

In [8]:
x_train

array([[-1.13572795, -0.88685592,  0.67357894,  0.52070558],
       [-0.80630243, -0.00971567,  0.45145467,  0.14531044],
       [ 1.77128416,  1.84743445,  0.24279248, -1.88374143],
       ...,
       [-0.38409993, -1.24886277,  0.84522042,  0.13092486],
       [-0.9232821 , -1.04155299,  1.54693117,  0.8830852 ],
       [ 1.70136528,  1.05824381, -1.20438076, -2.42285818]])

In [9]:
x_test

array([[ 1.20924389,  1.84743445, -0.61878043, -0.28968211],
       [-0.29401214, -0.39528045,  1.39211729,  0.76937061],
       [-0.64629575, -0.88607065,  1.00508258,  1.77019599],
       ...,
       [-0.99857936, -0.74629361,  1.76737267,  1.02146078],
       [ 1.02368993, -0.50992904, -1.64526378, -0.96443434],
       [-0.32090402, -1.13342892, -1.03442205,  0.0651622 ]])

In [10]:
y_train

array([[ 1.15069786],
       [ 0.79540777],
       [-1.30936356],
       ...,
       [ 0.27595724],
       [ 0.49346982],
       [-1.53508417]])

In [11]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=10 , random_state=0)
regressor.fit(x_train , y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [12]:
y_pred = regressor.predict(x_test)
y_pred = sc.inverse_transform(y_pred)

In [13]:
y_pred

array([433.722, 457.004, 462.624, ..., 469.807, 439.501, 460.419])

In [14]:
from sklearn.metrics import r2_score
print(f'The r2 score for  this model is:{ r2_score(y_test , y_pred)}')

The r2 score for  this model is:0.9612863481702605


In [ ]:
#thank you